#!/bin/sh

OUTPUT_DIR='./docs'
PLATFORM='MacOSX'
SDK_VERSION='10.13'



# Remove old docs
# ==============================================================================
rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"


# Generate index title
# ==============================================================================
echo "# ${PLATFORM} ${SDK_VERSION} SDK Frameworks" >> "${OUTPUT_DIR}/index.md"

echo 'This documentation is autogenerated using appledoc from the Framework ' \
    'header files in `/path/to/MacOSX.sdk/System/Library/Frameworks/`.'
>> "${OUTPUT_DIR}/index.md"

printf "\n" >> "${OUTPUT_DIR}/index.md"

echo 'Note: All rights of this documentation belong to Apple. You might need ' \
    'to accept Xcode’s Terms of Use or such to be allowed to browse these. ' \
    'I do not own any rights on this documentation.' \
>> "${OUTPUT_DIR}/index.md"


# Generate actual headers
# ==============================================================================
for frameworkPath in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/*.framework; do
    frameworkName=$(echo "$frameworkPath" | sed -E 's/.*\/(.+)\.framework/\1/')
    TITLE="${PLATFORM} ${SDK_VERSION} ${frameworkName} Framework"

    # Generate docs from Apple headers
    appledoc \
        --create-html \
        --no-create-docset \
        -p "${TITLE}" \
        -c 'Apple Inc.' \
        -o "${OUTPUT_DIR}" \
        --keep-undocumented-objects \
        --keep-undocumented-member \
        "$frameworkPath"

    # Rename output folder
    mv "${OUTPUT_DIR}/html" "${OUTPUT_DIR}/${frameworkName}"

    # Create link to this folder
    echo "* [${frameworkName} Framework Reference](./${frameworkName}/)" \
    >> "${OUTPUT_DIR}/index.md"
done


#
# === More paths to consider ===
#
# /Applications/Xcode.app/Contents/Developer/Library/Frameworks/*.framework/Headers
# /Applications/Xcode.app/Contents/Developer/Library/MigrationFrameworks/*.framework/Headers
# /Applications/Xcode.app/Contents/Developer/Platforms/*.platform/Developer/Library/Frameworks/*.framework/Headers
# /Applications/Xcode.app/Contents/Developer/Platforms/*.platform/Developer/Library/GPUToolsPlatform/Frameworks/*.framework/Headers
# /Applications/Xcode.app/Contents/Developer/Platforms/*.platform/Developer/SDKs/*.sdk/System/Library/Frameworks/*.framework/Headers
# /Applications/Xcode.app/Contents/Developer/Platforms/*.platform/Developer/SDKs/*.sdk/System/Library/Frameworks/*.framework/Frameworks/*.framework/Headers
# /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/Developer/Platforms/*.platform/Developer/Library/Frameworks/*.framework/Headers
