version: 2

general:
    branches:
        ignore:
            - gh-pages

jobs:
    build:
        macos:
            xcode: "9.2.0"

        steps:
            - checkout

            - run:
                name: 'Install appledoc (custom version)'
                command: |
                    cd ~ && \
                    git clone git://github.com/0bmxa/appledoc.git --branch 'feature/ISO-8859-support' && \
                    cd appledoc && \
                    ./install-appledoc.sh && \
                    cd ~/project

            - run:
                name: 'Generate docs for macOS'
                command: ./generate-docs.sh


            - run:
                name: 'Commit to GitHub pages'
                command: |
                    git checkout gh-pages && \
                    cp -R './docs/*' '.' && \
                    git add -A && \
                    git commit -m 'Automated commit by CI' && \
                    git push origin gh-pages
