version: 2

general:
    branches:
        ignore:
            - gh-pages

jobs:
    build:
        macos:
            xcode: "9.2.0"

        steps:
            - checkout

            - run:
                name: 'Set some git user details'
                command: |
                    git config --global user.name 'CI'
                    git config --global user.email 'ci@example.com'

            - run:
                name: 'Install appledoc (custom version)'
                command: |
                    cd ~ && \
                    git clone git://github.com/0bmxa/appledoc.git --branch 'feature/ISO-8859-support' && \
                    cd appledoc && \
                    ./install-appledoc.sh

            - run:
                name: 'Generate docs for macOS'
                command: |
                    cd ~/project && \
                    pwd && \
                    ./generate-appledoc.sh

            - run:
                name: 'Commit to GitHub pages'
                command: |
                    git checkout gh-pages && \
                    git rm -r . && \
                    git checkout HEAD -- .gitignore && \
                    mv ./docs/* . && \
                    git add -A && \
                    git commit -m 'Automated commit by CI' && \
                    git push origin gh-pages
